# Generated by Django 3.0.7 on 2020-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0002_auto_20200614_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketip',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maketip',
            name='outfit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maketip',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maketip',
            name='sexy',
            field=models.IntegerField(default=0),
        ),
    ]
