# Generated by Django 3.0.7 on 2020-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_auto_20200614_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketip',
            name='creativity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maketip',
            name='outfit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maketip',
            name='quality',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maketip',
            name='sexy',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
