# Generated by Django 3.0.7 on 2020-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0004_auto_20200614_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
