# Generated by Django 3.0.7 on 2020-06-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0005_auto_20200614_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.FileField(blank=True, help_text='Selecciona video', upload_to='media'),
        ),
    ]
